"""
Django settings for CraftedBySharath project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if present (local development)
load_dotenv(BASE_DIR / '.env')

# In-process RAG (LangChain + FAISS + Ollama). Defaults: `RAG/` next to this app (see `RAG/docs`, `RAG/faiss_index`).
_RAG_ROOT = Path(os.environ.get("RAG_ROOT", str(BASE_DIR / "RAG")))
RAG_DOCS_DIR = Path(os.environ.get("RAG_DOCS_DIR", str(_RAG_ROOT / "docs")))
RAG_INDEX_DIR = Path(os.environ.get("RAG_INDEX_DIR", str(_RAG_ROOT / "faiss_index")))
# LLM provider: "groq" (default, cloud-based, free tier) or "ollama" (local)
RAG_LLM_PROVIDER = os.environ.get("RAG_LLM_PROVIDER", "groq")

# Groq settings (used when RAG_LLM_PROVIDER=groq)
RAG_GROQ_API_KEY = os.environ.get("RAG_GROQ_API_KEY", "")
RAG_GROQ_MODEL = os.environ.get("RAG_GROQ_MODEL", "llama-3.3-70b-versatile")

# Ollama settings (used when RAG_LLM_PROVIDER=ollama)
RAG_OLLAMA_BASE_URL = os.environ.get("RAG_OLLAMA_BASE_URL", "http://127.0.0.1:11434")
RAG_OLLAMA_MODEL = os.environ.get("RAG_OLLAMA_MODEL", "llama3.2")

RAG_EMBED_MODEL = os.environ.get(
    "RAG_EMBED_MODEL",
    "sentence-transformers/all-MiniLM-L6-v2",
)
RAG_PORTFOLIO_NAME = os.environ.get("RAG_PORTFOLIO_NAME", "Sharath")
RAG_CHUNK_SIZE = int(os.environ.get("RAG_CHUNK_SIZE", "1200"))
RAG_CHUNK_OVERLAP = int(os.environ.get("RAG_CHUNK_OVERLAP", "200"))
RAG_TOP_K = int(os.environ.get("RAG_TOP_K", "6"))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set SECRET_KEY environment variable in production. Never commit a real key.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-38h4d1hxgrf82upndh7vvr2b!%fy@1ie!%9w%dd)(#=hf7xyqh',  # dev fallback only
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in production via environment variable.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Add your domain(s) here before going live, e.g. 'yourdomain.com', 'www.yourdomain.com'
_allowed = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()] or (['*'] if DEBUG else [])

# Trust HTTPS requests from your domain (required when behind a reverse proxy like Nginx)
_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CraftedBySharath.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CraftedBySharath.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# Where `collectstatic` gathers all static files for production serving (e.g. via Nginx)
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
